# Generated by Django 4.2.3 on 2023-07-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('creator_id', models.IntegerField()),
                ('id_done', models.BooleanField()),
            ],
        ),
    ]
