# Generated by Django 4.2.4 on 2023-08-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('creator_id', models.IntegerField()),
                ('is_done', models.BooleanField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
