# Generated by Django 4.2.4 on 2023-08-31 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_creator_id_note_creatorid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='creatorId',
            new_name='creator_id',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='isDone',
            new_name='is_done',
        ),
    ]
