# Generated by Django 4.2.4 on 2023-09-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_creatorid_note_creator_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_id',
            field=models.IntegerField(default=0),
        ),
    ]
